//
//  {CLASS}.h
//  Generated by SQLite Toolbox - http://itunes.apple.com/app/json-toolbox/id525015412
//
//  Created by {CURRENTUSER} on {DATE}
//

#import <Foundation/Foundation.h>
#import "FMDatabase.h"

@interface {CLASS} : NSObject
{
} // End of {CLASS}

- ({CLASS}*) initWithResultSet: (FMResultSet*) resultSet;
{METHOD_HEADERS}

{PROPERTIES}

@end
