//
//  <?= $table->name ?>.h
//  Generated by SQLite Professional - http://itunes.apple.com/app/json-toolbox/id525015412
//
//  Created by <?= $currentUser ?> on <?= $currentDate ?>
//

#import <Foundation/Foundation.h>
#import "FMDatabase.h"

@interface <?= $table->name ?> : NSObject
{
} // End of <?= $table->name ?>

<?php
  foreach($table->columns as $column)
  {
    printf("@property(nonatomic,retain) %s %s;\r\n", "NSString *", $column->name);
  }
?>

@end
