<?php /* Smarty version Smarty-3.1.13, created on 2013-03-02 20:31:41
         compiled from "templates/ModelHeader.tpl" */ ?>
<?php /*%%SmartyHeaderCode:99281977751329986cf9c27-79984659%%*/if(!defined('SMARTY_DIR')) exit('no direct access allowed');
$_valid = $_smarty_tpl->decodeProperties(array (
  'file_dependency' => 
  array (
    'f9789a55fd4a7c48a91dd77b6b2f8b740137d253' => 
    array (
      0 => 'templates/ModelHeader.tpl',
      1 => 1362270693,
      2 => 'file',
    ),
  ),
  'nocache_hash' => '99281977751329986cf9c27-79984659',
  'function' => 
  array (
  ),
  'version' => 'Smarty-3.1.13',
  'unifunc' => 'content_51329986d92096_25442767',
  'variables' => 
  array (
    'table' => 0,
  ),
  'has_nocache_code' => false,
),false); /*/%%SmartyHeaderCode%%*/?>
<?php if ($_valid && !is_callable('content_51329986d92096_25442767')) {function content_51329986d92096_25442767($_smarty_tpl) {?>//
//  <?php echo $_smarty_tpl->tpl_vars['table']->value->name;?>
.h
//  Generated by SQLite Professional - http://itunes.apple.com/app/json-toolbox/id525015412
//
//  Created by <<?php ?>?= $CurrentUser ?<?php ?>> on <<?php ?>?= $CurrentDate ?<?php ?>>
//

#import <Foundation/Foundation.h>
#import "FMDatabase.h"

@interface <?php echo $_smarty_tpl->tpl_vars['table']->value->name;?>
 : NSObject
{
} // End of <?php echo $_smarty_tpl->tpl_vars['table']->value->name;?>


@end
<?php }} ?>